insert into t_chapter values
(1, 'First article', '

Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lacinia vitae enim non efficitur. Donec ultricies metus quis neque lacinia, quis dictum felis ullamcorper. Donec sit amet nunc ut leo pellentesque pellentesque quis in nisi. Fusce eleifend sodales lorem, finibus posuere massa posuere sed. Vestibulum at magna cursus, interdum nulla id, auctor libero. Sed fermentum enim et risus consectetur ornare. Nam rhoncus risus ut sagittis imperdiet. Maecenas eget mauris fringilla, aliquam enim eu, mollis justo. Integer facilisis nulla libero, ac scelerisque lacus scelerisque at.

Fusce non sodales tortor. Ut consequat risus bibendum, maximus quam sit amet, placerat urna. Nam et nulla eros. Sed in urna dolor. Vivamus lacus urna, porta vel elementum ac, tincidunt ac sem. Nam pretium ipsum sem, ut placerat mi sagittis eu. Curabitur tempor justo a ligula sagittis, a blandit purus luctus. Phasellus quam leo, tincidunt volutpat eleifend eget, accumsan vel tellus. Maecenas ultricies consectetur mauris id efficitur.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris efficitur feugiat auctor. Donec sagittis, ipsum euismod efficitur porttitor, sapien odio malesuada ex, vel congue dolor lacus quis dolor. Pellentesque pharetra, diam nec congue imperdiet, libero nunc ultrices sem, ac dapibus metus purus semper sapien. Curabitur rhoncus tincidunt mi, at facilisis lectus accumsan pellentesque. Quisque varius, sapien at accumsan congue, quam leo suscipit orci, nec blandit nisl arcu eget leo. Phasellus pulvinar quis turpis sed porta.

Cras consectetur pellentesque velit, nec lacinia nibh tincidunt ut. Nulla sit amet feugiat velit, et commodo turpis. Suspendisse non ipsum velit. Donec feugiat dolor tortor. Morbi et molestie turpis, sit amet porta lectus. Nam maximus lacinia ex, faucibus pretium arcu dictum vehicula. Proin sit amet ultricies magna. Mauris consectetur egestas nunc eu iaculis. Donec eget tortor massa. Integer volutpat convallis mi vel venenatis.

Donec ut sem ut tortor facilisis viverra. Suspendisse rutrum magna ante, sed aliquet ex cursus quis. Aenean faucibus fringilla facilisis. Integer eget pulvinar enim. Morbi lobortis nunc est, a viverra velit facilisis eget. Vestibulum nec varius dolor, id feugiat nulla. Vestibulum fermentum viverra sem vitae commodo. Sed eleifend eros magna, eu convallis enim convallis eget. Vivamus sem nibh, ornare vitae varius quis, interdum sed libero.', '2017-04-03');
insert into t_chapter values
(2, 'Lorem ipsum', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut hendrerit mauris ac porttitor accumsan. Nunc vitae pulvinar odio, auctor interdum dolor. Aenean sodales dui quis metus iaculis, hendrerit vulputate lorem vestibulum. Suspendisse pulvinar, purus at euismod semper, nulla orci pulvinar massa, ac placerat nisi urna eu tellus. Fusce dapibus rutrum diam et dictum. Sed tellus ipsum, ullamcorper at consectetur vitae, gravida vel sem. Vestibulum pellentesque tortor et elit posuere vulputate. Sed et volutpat nunc. Praesent nec accumsan nisi, in hendrerit nibh. In ipsum mi, fermentum et eleifend eget, eleifend vitae libero. Phasellus in magna tempor diam consequat posuere eu eget urna. Fusce varius nulla dolor, vel semper dui accumsan vitae. Sed eget risus neque.
 

Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lacinia vitae enim non efficitur. Donec ultricies metus quis neque lacinia, quis dictum felis ullamcorper. Donec sit amet nunc ut leo pellentesque pellentesque quis in nisi. Fusce eleifend sodales lorem, finibus posuere massa posuere sed. Vestibulum at magna cursus, interdum nulla id, auctor libero. Sed fermentum enim et risus consectetur ornare. Nam rhoncus risus ut sagittis imperdiet. Maecenas eget mauris fringilla, aliquam enim eu, mollis justo. Integer facilisis nulla libero, ac scelerisque lacus scelerisque at.

Fusce non sodales tortor. Ut consequat risus bibendum, maximus quam sit amet, placerat urna. Nam et nulla eros. Sed in urna dolor. Vivamus lacus urna, porta vel elementum ac, tincidunt ac sem. Nam pretium ipsum sem, ut placerat mi sagittis eu. Curabitur tempor justo a ligula sagittis, a blandit purus luctus. Phasellus quam leo, tincidunt volutpat eleifend eget, accumsan vel tellus. Maecenas ultricies consectetur mauris id efficitur.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris efficitur feugiat auctor. Donec sagittis, ipsum euismod efficitur porttitor, sapien odio malesuada ex, vel congue dolor lacus quis dolor. Pellentesque pharetra, diam nec congue imperdiet, libero nunc ultrices sem, ac dapibus metus purus semper sapien. Curabitur rhoncus tincidunt mi, at facilisis lectus accumsan pellentesque. Quisque varius, sapien at accumsan congue, quam leo suscipit orci, nec blandit nisl arcu eget leo. Phasellus pulvinar quis turpis sed porta.

Cras consectetur pellentesque velit, nec lacinia nibh tincidunt ut. Nulla sit amet feugiat velit, et commodo turpis. Suspendisse non ipsum velit. Donec feugiat dolor tortor. Morbi et molestie turpis, sit amet porta lectus. Nam maximus lacinia ex, faucibus pretium arcu dictum vehicula. Proin sit amet ultricies magna. Mauris consectetur egestas nunc eu iaculis. Donec eget tortor massa. Integer volutpat convallis mi vel venenatis.

Donec ut sem ut tortor facilisis viverra. Suspendisse rutrum magna ante, sed aliquet ex cursus quis. Aenean faucibus fringilla facilisis. Integer eget pulvinar enim. Morbi lobortis nunc est, a viverra velit facilisis eget. Vestibulum nec varius dolor, id feugiat nulla. Vestibulum fermentum viverra sem vitae commodo. Sed eleifend eros magna, eu convallis enim convallis eget. Vivamus sem nibh, ornare vitae varius quis, interdum sed libero.', '2017-04-03');
insert into t_chapter values
(3, 'Lorem ipsum in french', "J’en dis autant de ceux qui, par mollesse d’esprit, c’est-à-dire par la crainte de la peine et de la douleur, manquent aux devoirs de la vie. Et il est très facile de rendre raison de ce que j’avance. Car, lorsque nous sommes tout à fait libres, et que rien ne nous empêche de faire ce qui peut nous donner le plus de plaisir, nous pouvons nous livrer entièrement à la volupté et chasser toute sorte de douleur ; mais, dans les temps destinés aux devoirs de la société ou à la nécessité des affaires, souvent il faut faire divorce avec la volupté, et ne se point refuser à la peine. La règle que suit en cela un homme sage, c’est de renoncer à de légères voluptés pour en avoir de plus grandes, et de savoir supporter des douleurs légères pour en éviter de plus fâcheuses.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lacinia vitae enim non efficitur. Donec ultricies metus quis neque lacinia, quis dictum felis ullamcorper. Donec sit amet nunc ut leo pellentesque pellentesque quis in nisi. Fusce eleifend sodales lorem, finibus posuere massa posuere sed. Vestibulum at magna cursus, interdum nulla id, auctor libero. Sed fermentum enim et risus consectetur ornare. Nam rhoncus risus ut sagittis imperdiet. Maecenas eget mauris fringilla, aliquam enim eu, mollis justo. Integer facilisis nulla libero, ac scelerisque lacus scelerisque at.

Fusce non sodales tortor. Ut consequat risus bibendum, maximus quam sit amet, placerat urna. Nam et nulla eros. Sed in urna dolor. Vivamus lacus urna, porta vel elementum ac, tincidunt ac sem. Nam pretium ipsum sem, ut placerat mi sagittis eu. Curabitur tempor justo a ligula sagittis, a blandit purus luctus. Phasellus quam leo, tincidunt volutpat eleifend eget, accumsan vel tellus. Maecenas ultricies consectetur mauris id efficitur.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris efficitur feugiat auctor. Donec sagittis, ipsum euismod efficitur porttitor, sapien odio malesuada ex, vel congue dolor lacus quis dolor. Pellentesque pharetra, diam nec congue imperdiet, libero nunc ultrices sem, ac dapibus metus purus semper sapien. Curabitur rhoncus tincidunt mi, at facilisis lectus accumsan pellentesque. Quisque varius, sapien at accumsan congue, quam leo suscipit orci, nec blandit nisl arcu eget leo. Phasellus pulvinar quis turpis sed porta.

Cras consectetur pellentesque velit, nec lacinia nibh tincidunt ut. Nulla sit amet feugiat velit, et commodo turpis. Suspendisse non ipsum velit. Donec feugiat dolor tortor. Morbi et molestie turpis, sit amet porta lectus. Nam maximus lacinia ex, faucibus preatium arcu dictum vehicula. Proin sit amet ultricies magna. Mauris consectetur egestas nunc eu iaculis. Donec eget tortor massa. Integer volutpat convallis mi vel venenatis.

Donec ut sem ut tortor facilisis viverra. Suspendisse rutrum magna ante, sed aliquet ex cursus quis. Aenean faucibus fringilla facilisis. Integer eget pulvinar enim. Morbi lobortis nunc est, a viverra velit facilisis eget. Vestibulum nec varius dolor, id feugiat nulla. Vestibulum fermentum viverra sem vitae commodo. Sed eleifend eros magna, eu convallis enim convallis eget. Vivamus sem nibh, ornare vitae varius quis, interdum sed libero.", '2017-04-03');


insert into t_comment values (1,'bonjour',1,'2017-04-03','Simon');
insert into t_user values
(3, 'admin', '$2y$13$A8MQM2ZNOi99EW.ML7srhOJsCaybSbexAj/0yXrJs4gQ/2BqMMW2K', 'EDDsl&fBCJB|a5XUtAlnQN8', 'ROLE_ADMIN');